# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: docker pull katalonstudio/katalon
  displayName: 'Pull katalon studio images'
- script: docker run -t --rm -v "$(pwd)":/katalon/katalon/source katalonstudio/katalon katalonc.sh -projectPath="/loan test broser start.prj" -retry=0 -testSuitePath="Test Suites/test maximize windows" -browserType="Chrome" -executionProfile="default" -apiKey="ce1504db-a920-429e-92da-894ead237b33" -testOps.serverUrl="https://testops.katalon.io" -orgID=89151 --config  -webui.autoUpdateDrivers=true
  displayName: 'Runnning Katalon TS_RegressionTest'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
